/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type HomePage = {
    _id: string;
    _type: 'homePage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    hero: {
        heroTitle: InternationalizedArrayString;
        heroSubtitle: InternationalizedArrayText;
        primaryCta: CallToAction;
        secondaryCta: CallToAction;
        image: AccessibleImage;
    };
    carousel: {
        title: InternationalizedArrayString;
        subtitle?: InternationalizedArrayText;
        cta?: CallToAction;
        images: Array<{
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
            _key: string;
        }>;
    };
};

export type SanityImageCrop = {
    _type: 'sanity.imageCrop';
    top: number;
    bottom: number;
    left: number;
    right: number;
};

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot';
    x: number;
    y: number;
    height: number;
    width: number;
};

export type CallToAction = {
    _type: 'callToAction';
    label: InternationalizedArrayString;
    url: '/menu' | '/gallery' | '/#hero' | '/#story' | '/#menu' | '/#order' | '/#gallery' | '/#contact';
    variant: 'primary' | 'secondary';
};

export type InternationalizedArrayText = Array<
    {
        _key: string;
    } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
    {
        _key: string;
    } & InternationalizedArrayStringValue
>;

export type AccessibleImage = {
    _type: 'accessibleImage';
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: InternationalizedArrayString;
};

export type MediaTag = {
    _id: string;
    _type: 'media.tag';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: Slug;
};

export type Slug = {
    _type: 'slug';
    current: string;
    source?: string;
};

export type InternationalizedArrayTextValue = {
    _type: 'internationalizedArrayTextValue';
    value?: string;
    language: string;
};

export type InternationalizedArrayStringValue = {
    _type: 'internationalizedArrayStringValue';
    value?: string;
    language: string;
};

export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch';
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: 'sanity.imagePalette';
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions';
    height: number;
    width: number;
    aspectRatio: number;
};

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata';
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    thumbHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type SanityFileAsset = {
    _id: string;
    _type: 'sanity.fileAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData';
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageAsset = {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash: string;
    extension: string;
    mimeType: string;
    size: number;
    assetId: string;
    uploadId?: string;
    path: string;
    url: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: 'geopoint';
    lat?: number;
    lng?: number;
    alt?: number;
};

export type AllSanitySchemaTypes =
    | SanityImageAssetReference
    | HomePage
    | SanityImageCrop
    | SanityImageHotspot
    | CallToAction
    | InternationalizedArrayText
    | InternationalizedArrayString
    | AccessibleImage
    | MediaTag
    | Slug
    | InternationalizedArrayTextValue
    | InternationalizedArrayStringValue
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageMetadata
    | SanityFileAsset
    | SanityAssetSourceData
    | SanityImageAsset
    | Geopoint;

// Source: src/sanity/queries/home-page.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0] {        _id,        "title": hero.heroTitle[language == $locale][0].value,        "subtitle": hero.heroSubtitle[language == $locale][0].value,        "primaryCta": hero.primaryCta {            "label": label[language == $locale][0].value,            url,            variant        },        "secondaryCta": hero.secondaryCta {            "label": label[language == $locale][0].value,            url,            variant        },        "image": hero.image {            "assetId": asset->_id,            "lqip": asset->metadata.lqip,            "width": asset->metadata.dimensions.width,            "height": asset->metadata.dimensions.height,            crop {                top,                right,                bottom,                left            },            hotspot {                x,                y,                width,                height            },            "alt": alt[language == $locale][0].value        },        "carousel": carousel {            "title": title[language == $locale][0].value,            "subtitle": subtitle[language == $locale][0].value,            "cta": cta {                "label": label[language == $locale][0].value,                "url": "/gallery",                variant            },            "images": images[] {                _key,                "assetId": asset->_id,                "width": asset->metadata.dimensions.width,                "height": asset->metadata.dimensions.height,                "lqip": asset->metadata.lqip,                "alt": coalesce(asset->altText, "")            }        }    }
export type HOME_PAGE_QUERY_RESULT =
    | {
          _id: 'homePage';
          title: null;
          subtitle: null;
          primaryCta: null;
          secondaryCta: null;
          image: null;
          carousel: null;
      }
    | {
          _id: 'homePage';
          title: string | null;
          subtitle: string | null;
          primaryCta: {
              label: string | null;
              url: '/#contact' | '/#gallery' | '/#hero' | '/#menu' | '/#order' | '/#story' | '/gallery' | '/menu';
              variant: 'primary' | 'secondary';
          };
          secondaryCta: {
              label: string | null;
              url: '/#contact' | '/#gallery' | '/#hero' | '/#menu' | '/#order' | '/#story' | '/gallery' | '/menu';
              variant: 'primary' | 'secondary';
          };
          image: {
              assetId: string | null;
              lqip: string | null;
              width: number | null;
              height: number | null;
              crop: {
                  top: number;
                  right: number;
                  bottom: number;
                  left: number;
              } | null;
              hotspot: {
                  x: number;
                  y: number;
                  width: number;
                  height: number;
              } | null;
              alt: string | null;
          };
          carousel: {
              title: string | null;
              subtitle: string | null;
              cta: {
                  label: string | null;
                  url: '/gallery';
                  variant: 'primary' | 'secondary';
              } | null;
              images: Array<{
                  _key: string;
                  assetId: string | null;
                  width: number | null;
                  height: number | null;
                  lqip: string | null;
                  alt: string | '';
              }>;
          };
      }
    | null;
